[logging]
level = "debug"

[provider]
first_gpu = 0
class = "Smartsim"
device = "GPU"
model_backend = "TORCH"
model_path = "/rwthfs/rz/cluster/hpcwork/ro092286/MMCP_2026_Artifact_Hybrid_Inference/input/transformer_inference_scripted_fw2.pt"
model_name = "mmcp_transformer"
nodes = 1
num_gpus = 1
batch_size = 1
command_timeout = 900
socket_timeout = 900
model_timeout = 900000


[normalization]
class = "MinMax"
input_min = 0.0
input_max = 1.0
output_min = 0.0
output_max = 1.0

[behavior]
class = "Default"

[application]
class = "ModuleTestApplication"
